// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartOnApp.WebAPI.RepositoryLayer;

namespace SmartOnApp.WebAPI.Migrations
{
    [DbContext(typeof(SmartOnDbContext))]
    partial class SmartOnDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("SmartOnApp.Shared.DomainLayer.Models.IoTDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("iot_device_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("IoTDeviceName")
                        .HasColumnType("longtext")
                        .HasColumnName("iot_device_name");

                    b.Property<string>("IoTDeviceType")
                        .HasColumnType("longtext")
                        .HasColumnName("iot_device_type");

                    b.Property<int>("McuId")
                        .HasColumnType("int")
                        .HasColumnName("mcu_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("McuId");

                    b.ToTable("iot_device");
                });

            modelBuilder.Entity("SmartOnApp.Shared.DomainLayer.Models.Mcu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mcu_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Location")
                        .HasColumnType("longtext")
                        .HasColumnName("location");

                    b.Property<string>("McuHostname")
                        .HasColumnType("longtext")
                        .HasColumnName("mcu_hostname");

                    b.Property<string>("McuIp")
                        .HasColumnType("longtext")
                        .HasColumnName("mcu_ip");

                    b.Property<string>("McuMacAddress")
                        .HasColumnType("longtext")
                        .HasColumnName("mcu_mac_address");

                    b.Property<string>("McuName")
                        .HasColumnType("longtext")
                        .HasColumnName("mcu_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("mcu");
                });

            modelBuilder.Entity("SmartOnApp.Shared.DomainLayer.Models.Ldr", b =>
                {
                    b.HasBaseType("SmartOnApp.Shared.DomainLayer.Models.IoTDevice");

                    b.Property<int>("Brightness")
                        .HasColumnType("int")
                        .HasColumnName("brightness");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp");

                    b.ToTable("ldr");
                });

            modelBuilder.Entity("SmartOnApp.Shared.DomainLayer.Models.Light", b =>
                {
                    b.HasBaseType("SmartOnApp.Shared.DomainLayer.Models.IoTDevice");

                    b.Property<bool>("LightIsOn")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("light_is_on");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp");

                    b.ToTable("light");
                });

            modelBuilder.Entity("SmartOnApp.Shared.DomainLayer.Models.Pir", b =>
                {
                    b.HasBaseType("SmartOnApp.Shared.DomainLayer.Models.IoTDevice");

                    b.Property<bool>("MotionIsDetected")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("motion_is_detected");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp");

                    b.ToTable("pir");
                });

            modelBuilder.Entity("SmartOnApp.Shared.DomainLayer.Models.Servo", b =>
                {
                    b.HasBaseType("SmartOnApp.Shared.DomainLayer.Models.IoTDevice");

                    b.Property<int>("ServoCurrentPosition")
                        .HasColumnType("int")
                        .HasColumnName("servo_current_position");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp");

                    b.ToTable("servo");
                });

            modelBuilder.Entity("SmartOnApp.Shared.DomainLayer.Models.IoTDevice", b =>
                {
                    b.HasOne("SmartOnApp.Shared.DomainLayer.Models.Mcu", "Mcu")
                        .WithMany("IoTDevices")
                        .HasForeignKey("McuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mcu");
                });

            modelBuilder.Entity("SmartOnApp.Shared.DomainLayer.Models.Ldr", b =>
                {
                    b.HasOne("SmartOnApp.Shared.DomainLayer.Models.IoTDevice", null)
                        .WithOne()
                        .HasForeignKey("SmartOnApp.Shared.DomainLayer.Models.Ldr", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartOnApp.Shared.DomainLayer.Models.Light", b =>
                {
                    b.HasOne("SmartOnApp.Shared.DomainLayer.Models.IoTDevice", null)
                        .WithOne()
                        .HasForeignKey("SmartOnApp.Shared.DomainLayer.Models.Light", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartOnApp.Shared.DomainLayer.Models.Pir", b =>
                {
                    b.HasOne("SmartOnApp.Shared.DomainLayer.Models.IoTDevice", null)
                        .WithOne()
                        .HasForeignKey("SmartOnApp.Shared.DomainLayer.Models.Pir", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartOnApp.Shared.DomainLayer.Models.Servo", b =>
                {
                    b.HasOne("SmartOnApp.Shared.DomainLayer.Models.IoTDevice", null)
                        .WithOne()
                        .HasForeignKey("SmartOnApp.Shared.DomainLayer.Models.Servo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartOnApp.Shared.DomainLayer.Models.Mcu", b =>
                {
                    b.Navigation("IoTDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
